Task 1
Nikita-Fast/formal-lang-course pull request #1
Opened 2022-09-14 16:26 UTC by Nikita-Fast

- [x] Сделать **приватный** `fork` данного репозитория.
- [x] Добавить ссылку на ваш `fork` в [таблицу](https://docs.google.com/spreadsheets/d/1IXeAhVb_cRRQf0UwHjw2AeBqNwpcY-XcnVs3-t9HBYc/edit#gid=0).
- [x] Добавить в совладельцы форка одного из ассистентов (чтобы узнать, кого именно, нужно посмотреть в [таблицу](https://docs.google.com/spreadsheets/d/1IXeAhVb_cRRQf0UwHjw2AeBqNwpcY-XcnVs3-t9HBYc/edit#gid=0))
- [x] Реализовать модуль, предоставляющий перечисленные ниже возможности. Для работы с графами использовать [cfpq-data](https://jetbrains-research.github.io/CFPQ_Data/tutorial.html#graphs). Данный модуль в дальнейшем будет расширяться. Функции, которые необходимо реализовать:
  - [x] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах. Для получения графа по имени использовать [эту функцию](https://jetbrains-research.github.io/CFPQ_Data/tutorial.html#get-a-real-graph).
  - [x] По количеству вершин в циклах и именам меток строить [граф из двух циклов](https://jetbrains-research.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.generators.labeled_two_cycles_graph.html#cfpq_data.graphs.generators.labeled_two_cycles_graph) и сохранять его в указанный файл в формате DOT (использовать pydot).
- [x] Добавить необходимые тесты.
- [x] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.

2022-09-17 15:17 UTC, vadyushkins requested changes
Если исправите замечания будет зачтено

2022-09-17 15:17 UTC, vadyushkins commented on .github/workflows/tests.yml
> +    runs-on: ubuntu-latest
Добавьте windows, macos

2022-09-17 15:17 UTC, vadyushkins commented on .github/workflows/tests.yml
> +        python-version: ["3.8.10"]
3.9? 3.10?

2022-09-17 15:17 UTC, vadyushkins commented on project/graph_tools.py
> +    """
Вы уверены, что и дальше для всех публичных функций сможете поддерживать документацию? На мой взгляд Вам будет проще писать понятный читабельный код, но решайте сами.

2022-09-17 15:17 UTC, vadyushkins commented on project/graph_tools.py
> +def create_and_save_two_cycles_graph(n, m, labels, path):
n, m -- нечитабельные имена параметров

2022-09-17 15:17 UTC, vadyushkins commented on tests/task_1/test_graph_tools.py
> +"""
Вынесите в отдельный файл данные, которые ожидаете. Например JSON.
Добавьте больше графов. В том числе крайние случаи

2022-09-17 15:17 UTC, vadyushkins commented on tests/task_1/test_graph_tools.py
> +"""
К остальным тестам замечания так же относятся

2022-09-21 17:22 UTC, Nikita-Fast commented
- поменял .yml файл  
- переименовал имена параметров на более понятные 
- добавил больше тестовых графов и сложил их в отдельные файлы

2022-09-22 09:04 UTC, vadyushkins approved these changes
зачтено, но нужно исправить замечания\ответить на вопросы

2022-09-22 09:04 UTC, vadyushkins commented on requirements.txt
> +networkx~=2.6.2
networkx уже есть в зависимостях у cfpq-data

2022-09-22 09:04 UTC, vadyushkins commented on requirements.txt
> +pytest~=7.1.3
зачем Вам понадобилось выделять конкретные версии?

2022-09-28 14:31 UTC, merged